language: php

php:
  - 5.5

before_script:
  - echo 'Europe/Stockholm' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml src/

after_script:
 - vendor/bin/coveralls -v
