language: php

php:
  - 5.5

before_script:
  - echo 'Europe/Stockholm' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - composer install --dev

script: vendor/bin/phpunit src/
